//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kuliner.Core.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInstance
    {
        public System.Guid ProductInstanceId { get; set; }
        public System.Guid ProductId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
